Repository antstackio/hover-design, pull requests merged in 2022-08, with the labels that each got.

#26 Gh actions/publish on release
  .github/workflows/npm-publish.yml
  lib/package.json
Labels: enhancement

#27 Chores/release v0.1.6
  .github/workflows/npm-publish.yml
Labels: enhancement

#25 [HOV-10] Flex component
  docs/docs/components/flex.mdx
  examples/vanilla-extract-react/package.json
  lib/src/components/Flex/Flex.tsx
  lib/src/components/Flex/flex.types.ts
  lib/src/components/Flex/index.ts
  lib/src/index.ts
  netlify.toml
  pnpm-lock.yaml
Labels: New Component

#57 Adds git playbook + adds steps for forking in contribution
  docs/docs/contribution.md
  docs/docs/wiki/playbooks/_category_.json
  docs/docs/wiki/playbooks/git_playbook.md
Labels: documentation

#53 HOV-16 | Divider component
  docs/docs/components/divider.mdx
  lib/package.json
  lib/src/components/Divider/Divider.tsx
  lib/src/components/Divider/divider.css.ts
  lib/src/components/Divider/divider.types.ts
  lib/src/components/Divider/index.ts
  lib/src/index.ts
  pnpm-lock.yaml
Labels: New Component

#60 bumps docusaurus to 2.0 (stable)
  docs/package.json
  lib/package.json
  pnpm-lock.yaml
Labels: documentation, enhancement

#51 HOV-15 | TextArea Component
  docs/docs/components/card.mdx
  docs/docs/components/list.mdx
  docs/docs/components/switch.mdx
  docs/docs/components/text-area.mdx
  examples/vanilla-extract-react/src/components/appWraper/StyleWrapper.tsx
  examples/vanilla-extract-react/src/components/container/container.tsx
  examples/vanilla-extract-react/src/components/pageMain/PageMain.tsx
  lib/src/components/TextArea/TextArea.tsx
  lib/src/components/TextArea/index.ts
  lib/src/components/TextArea/text-area.css.ts
  lib/src/components/TextArea/text-area.types.ts
  lib/src/index.ts
Labels: New Component

#63 Tab component v1
  lib/src/components/Tab/Tab.tsx
  lib/src/components/Tab/index.tsx
  lib/src/components/Tab/tab.css.ts
  lib/src/components/Tab/tab.types.ts
  lib/src/index.ts
Labels: New Component

#68 Tab docs
  docs/docs/components/tab.mdx
  lib/package.json
  pnpm-lock.yaml
Labels: documentation, DO NOT MERGE

#58 Adds Accordion
  docs/docs/components/accordion.mdx
  docs/docs/components/icon.mdx
  docs/src/components/examples/AccordionAdvancedUsage.tsx
  examples/vanilla-extract-react/package.json
  lib/src/components/Accordion/Accordion.tsx
  lib/src/components/Accordion/AccordionContent/AccordionContent.tsx
  lib/src/components/Accordion/AccordionGroup/AccordionGroup.tsx
  lib/src/components/Accordion/AccordionSummary/AccordionSummary.tsx
  lib/src/components/Accordion/AccordionSummary/accordionSummary.types.ts
  lib/src/components/Accordion/accordion.global.styles.css.ts
  lib/src/components/Accordion/accordion.styles.css.ts
  lib/src/components/Accordion/accordion.types.ts
  lib/src/components/Accordion/index.ts
  lib/src/components/Icon/Icon.tsx
  lib/src/components/Icon/icon.type.ts
  lib/src/components/Icon/index.ts
  lib/src/components/_internal/Icons/Chevron.tsx
  lib/src/index.ts
Labels: New Component

#77 Adds useClickOutside and useBodyScroll Hooks
  lib/src/hooks/useBodyScrollLock.tsx
  lib/src/hooks/useClickOutside.tsx
Labels: enhancement
