Repository antstackio/hover-design, pull requests merged in 2022-09, with the labels that each got.

#75 Tabs v2
  docs/docs/components/tabs.mdx
  docs/package.json
  lib/src/components/Tab/Tabs.tsx
  lib/src/components/Tab/tabs.css.ts
  lib/src/components/Tab/tabs.types.ts
  pnpm-lock.yaml
Labels: enhancement

#82 Adds Modal component
  docs/docs/components/modal.mdx
  docs/src/components/examples/ModalExample.tsx
  lib/src/components/Modal/Modal.stories.tsx
  lib/src/components/Modal/Modal.tsx
  lib/src/components/Modal/index.ts
  lib/src/components/Modal/modal.constants.ts
  lib/src/components/Modal/modal.styles.css.ts
  lib/src/components/Modal/modal.types.ts
  lib/src/components/_internal/Icons/Close.tsx
  lib/src/index.ts
  lib/src/utils/object-utils.ts
Labels: documentation, enhancement, New Component

#84 Adds Dialog Component
  docs/docs/components/dialog.mdx
  docs/src/components/examples/DialogExample.tsx
  lib/src/components/Dialog/Dialog.stories.tsx
  lib/src/components/Dialog/Dialog.tsx
  lib/src/components/Dialog/dialog.styles.css.ts
  lib/src/components/Dialog/dialog.types.ts
  lib/src/components/Dialog/index.ts
  lib/src/index.ts
Labels: documentation, New Component

#83 Select component
  docs/docs/components/select.mdx
  lib/src/components/Select/Select.tsx
  lib/src/components/Select/index.ts
  lib/src/components/Select/select.css.ts
  lib/src/components/Select/select.types.ts
  lib/src/components/_internal/Icons/ArrowDown.tsx
  lib/src/components/_internal/Icons/Clear.tsx
  lib/src/hooks/useClickOutside.tsx
  lib/src/index.ts
Labels: New Component

#88 Native select component
  docs/docs/components/nativeSelect.mdx
  lib/src/components/NativeSelect/NativeSelect.tsx
  lib/src/components/NativeSelect/index.ts
  lib/src/components/NativeSelect/nativeSelect.css.ts
  lib/src/components/NativeSelect/nativeSelect.types.ts
  lib/src/index.ts
Labels: New Component

#85 Adds Radio and RadioGroup [v1]
  docs/docs/components/radio.mdx
  docs/src/components/examples/RadioExample.tsx
  examples/vanilla-extract-react/src/App.tsx
  lib/src/components/Radio/Radio.stories.tsx
  lib/src/components/Radio/Radio.tsx
  lib/src/components/Radio/RadioGroup/RadioGroup.tsx
  lib/src/components/Radio/index.ts
  lib/src/components/Radio/radio.global.styles.css.ts
  lib/src/components/Radio/radio.styles.css.ts
  lib/src/components/Radio/radio.types.ts
  lib/src/components/_internal/Icons/SvgDot.tsx
  lib/src/index.ts
  pnpm-lock.yaml
Labels: New Component

#92 Fixing broken link
  docs/docs/contribution.md
Labels: bug

#101 Fix accordion docs
  docs/docs/components/accordion.mdx
Labels: bug, documentation

#107 HOV-41 | Update version in intro md
  docs/docs/intro.md
Labels: bug, documentation

#109 Divider Docs
  docs/docs/components/divider.mdx
  pnpm-lock.yaml
Labels: documentation

#97 HOV-44 | Select component - MultiSelect
  docs/docs/components/select.mdx
  lib/src/components/NativeSelect/NativeSelect.tsx
  lib/src/components/Select/Pill/Pill.tsx
  lib/src/components/Select/Pill/pill.css.ts
  lib/src/components/Select/Select.tsx
  lib/src/components/Select/select.css.ts
  lib/src/components/Select/select.global.styles.css.ts
  lib/src/components/Select/select.types.ts
  lib/src/components/_internal/Icons/ArrowDown.tsx
  lib/src/components/_internal/Icons/Clear.tsx
Labels: enhancement

#108 HOV-11 | Popover component
  docs/docs/components/popover.mdx
  lib/src/components/Popover/Popover.tsx
  lib/src/components/Popover/index.ts
  lib/src/components/Popover/popover.css.ts
  lib/src/components/Popover/popover.types.ts
  lib/src/components/_internal/Constants/constants.ts
  lib/src/hooks/useTrapFocus.tsx
  lib/src/index.ts
Labels: New Component

#102 HOV-42 | Adds Grid and docs
  docs/docs/components/grid.mdx
  lib/src/components/Grid/Grid.tsx
  lib/src/components/Grid/grid.types.ts
  lib/src/components/Grid/index.ts
  lib/src/index.ts
Labels: New Component

#106 HOV-39 | Fixes to list
  docs/docs/components/list.mdx
  lib/src/components/List/List.tsx
  lib/src/components/List/list.css.ts
  lib/src/components/ListItem/ListItem.tsx
  lib/src/components/ListItem/list-item.css.ts
Labels: bug

#119 HOV-51 | Enhancements for Card
  lib/src/components/Card/Card.tsx
  lib/src/components/Card/card.styles.css.ts
  lib/src/components/Card/card.types.ts
  lib/src/components/Card/index.ts
Labels: bug, enhancement

#120 HOV-46 | Adds Readme for `lib` folder and keywords
  lib/Readme.md
  lib/package.json
Labels: documentation

#121 HOV-45 | Fixes Icon component to have lesser base values
  lib/src/components/Icon/Icon.tsx
  lib/src/components/_internal/Icons/ArrowDown.tsx
  lib/src/components/_internal/Icons/CheckIcon.tsx
  lib/src/components/_internal/Icons/Chevron.tsx
  lib/src/components/_internal/Icons/Clear.tsx
  lib/src/components/_internal/Icons/Close.tsx
  lib/src/components/_internal/Icons/DashIcon.tsx
  lib/src/components/_internal/Icons/SvgDot.tsx
Labels: bug, enhancement

#122 HOV-56 | sets up vitest and action for test
  .github/workflows/run-tests-on-pr.yml
  lib/package.json
  lib/src/utils/tests/object-utils.test.ts
  lib/vite.config.ts
  lib/vitest.config.ts
  package.json
  pnpm-lock.yaml
  turbo.json
Labels: enhancement

#118 HOV-49 | adjustments to button
  lib/src/components/Button/Button.tsx
  lib/src/components/Button/button.styles.css.ts
  lib/src/components/Button/button.types.ts
  lib/src/components/Button/index.ts
Labels: bug, enhancement

#126 HOV-52 | Adds Loader Component
  docs/docs/components/loader.mdx
  lib/src/components/Button/Button.stories.tsx
  lib/src/components/Loader/Loader.tsx
  lib/src/components/Loader/Spinner/Spinner.tsx
  lib/src/components/Loader/Spinner/spinner.styles.css.ts
  lib/src/components/Loader/Spinner/spinner.types.ts
  lib/src/components/Loader/index.ts
  lib/src/components/Loader/loader.styles.css.ts
  lib/src/components/Loader/loader.types.ts
  lib/src/index.ts
Labels: New Component

#124 HOV-29 | Adds Alert component
  docs/docs/components/alert.mdx
  lib/src/components/Alert/Alert.tsx
  lib/src/components/Alert/alert.styles.css.ts
  lib/src/components/Alert/alert.types.ts
  lib/src/components/Alert/index.ts
  lib/src/components/_internal/Icons/AlertTriangle.tsx
  lib/src/components/_internal/Icons/CheckCircle.tsx
  lib/src/components/_internal/Icons/InfoCircle.tsx
  lib/src/index.ts
Labels: New Component

#129 Duplication fix - Popover and Tooltip
  lib/src/components/Popover/popover.types.ts
  lib/src/components/Tooltip/Tooltip.tsx
  lib/src/components/Tooltip/tooltip.styles.css.ts
  lib/src/components/Tooltip/tooltip.types.ts
Labels: bug, High priority

#127 Removes code smells
  examples/vanilla-extract-react/src/App.tsx
  lib/src/components/Accordion/Accordion.tsx
  lib/src/components/Input/input.styles.css.ts
  lib/src/components/Modal/Modal.tsx
  lib/src/components/NativeSelect/NativeSelect.tsx
  lib/src/components/NativeSelect/nativeSelect.types.ts
  lib/src/components/Popover/Popover.tsx
  lib/src/components/Popover/popover.styles.css.ts
  lib/src/components/Select/select.css.ts
  lib/src/components/Select/select.types.ts
  lib/src/components/Table/Table.css.ts
  lib/src/components/Table/Tfoot/Tfoot.css.ts
  lib/src/components/Table/Thead/Thead.css.ts
  lib/src/components/TextArea/text-area.css.ts
  lib/src/components/Tooltip/tooltip.styles.css.ts
  lib/src/components/Tooltip/tooltip.types.ts
  lib/src/components/reset/reset.css.ts
  lib/src/hooks/useBodyScrollLock.tsx
Labels: bug
