Repository antstackio/hover-design, pull requests merged in 2022-10, with the labels that each got.

#90 HOV-3x | DateTimePicker Component
  docs/docs/components/dateAndTime.mdx
  docs/docs/components/input.mdx
  lib/src/components/DateAndTime/DateTimePicker.tsx
  lib/src/components/DateAndTime/date-time-picker.types.ts
  lib/src/components/DateAndTime/index.ts
  lib/src/index.ts
Labels: documentation, New Component

#130 Adds Banner Component and Alert Component Changes
  docs/docs/components/alert.mdx
  docs/docs/components/banner.mdx
  lib/src/components/Alert/Alert.tsx
  lib/src/components/Alert/alert.styles.css.ts
  lib/src/components/Alert/alert.types.ts
  lib/src/components/Banner/Banner.tsx
  lib/src/components/Banner/banner.global.styles.css.ts
  lib/src/components/Banner/banner.styles.css.ts
  lib/src/components/Banner/banner.types.ts
  lib/src/components/Banner/index.tsx
  lib/src/components/Icon/Icon.tsx
  lib/src/index.ts
Labels: documentation, enhancement, New Component

#131 Select Value Changes
  docs/docs/components/select.mdx
  lib/src/components/Select/Select.tsx
  lib/src/components/Select/select.types.ts
Labels: enhancement, High priority, DO NOT MERGE

#134 HOV-58 | Adds Progress component
  docs/docs/components/progress.mdx
  lib/src/components/Progress/Progress.tsx
  lib/src/components/Progress/index.ts
  lib/src/components/Progress/progress.styles.css.ts
  lib/src/components/Progress/progress.types.ts
  lib/src/index.ts
Labels: New Component

#135 NOTE: MERGE LAST!!! | Bumps lib to 0.1.10 for release
  lib/package.json
Labels: DO NOT MERGE

#137 BUG: Options not re rendering fix
  lib/src/components/Select/Select.tsx
Labels: bug, High priority

#138 BUG: Select Component keyboard controls error handled
  lib/src/components/Select/Select.tsx
Labels: bug, High priority, DO NOT MERGE

#140 Minor Select Change
  lib/src/components/Select/Select.tsx
Labels: bug
